sudo: false
git:
  depth: 1
language: ruby
bundler_args: --without development testext production --deployment --jobs=4 --retry=5
cache: bundler
dist: precise

rvm:
  - jruby-9.1.5.0

matrix:
  include:
    - { rvm: jruby-9.1.5.0 }

env:
  - JRUBY_OPTS="--dev -J-Xmx900m" DISPLAY=:99.0 LOGGER_LEVEL=WARN TRAVIS_NODE_VERSION="4"

before_install:
  - gem update --system 2.4.5

before_script:
  - ./script/front-end-build.sh

script:
  - ./script/front-end-tests.sh
  - RAILS_ENV=test bundle exec rspec
